### ISSUE TITLE
question for zk watcher package

### ISSUE THREAD

**Issue by huanghuangzym** [aeraki-framework/dubbo2istio#1]
hello 
i want to use this pkg to mod the genrate serviceentry for test
but i can not find the 
github.com/aeraki-framework/double2istio/pkg/dubbo/zk/watcher  pkg
can u tell me  where to find this package?

**Comment by zhaohuabing** [comment]
It's under test now and will be available soon.

**Comment by zhaohuabing** [comment]
Code uploaded.
