### ISSUE TITLE
dubbo2istio支持获取所有dubbo服务信息

### ISSUE THREAD

**Issue by FeiYing9** [aeraki-framework/dubbo2istio#18]
dubbo2istio从zk获取dubbo相应zk信息解析后，转换成SE，多处代码例如：

https://github.com/aeraki-framework/dubbo2istio/blob/d74da095573c36774a7d6b588a5ebdfab08b634b/pkg/dubbo/common/conversion.go#L51-L55 

https://github.com/aeraki-framework/dubbo2istio/blob/d74da095573c36774a7d6b588a5ebdfab08b634b/pkg/dubbo/common/conversion.go#L75

均要求获取属性`aeraki_*`，如果其他dubbo服务注册时没有以`aeraki_`为前缀或者根本没有这些属性，根据代码逻辑直接忽略该provider，导致dubbo2istio没有获取到该provider信息

这些逻辑在运行aeraki样例时没问题，其他公司内部已运行的老服务就会进入上述逻辑

不知道上述逻辑是否正确？

若正确，本项目应该设置一个标准，dubbo2istio提取的dubbo对象必须注册`xxx`属性，这样的话业务端其实涉及到了改造工作

或者粗暴一点，根据属性`application`直接从k8s环境找到该微服务，自动提取`namespace` \ `label`等属性？

由于本人不太熟悉dubbo协议，不知属性`application`是否代表该微服务的`service`，只不过这样又要定标准`application`为`service`了。

**Comment by FeiYing9** [comment]
另外，根据 dubbo [官网](https://dubbo.apache.org/zh/docs/v2.7/user/references/registry/zookeeper/) zookeeper 的根节点是可以配置的，默认情况下是`/dubbo`, 因此根节点的属性通过环境变量等的方式进行配置更合适

**Comment by zhaohuabing** [comment]
均要求获取属性aeraki_*，如果其他dubbo服务注册时没有以aeraki_为前缀或者根本没有这些属性，根据代码逻辑直接忽略该provider，导致dubbo2istio没有获取到该provider信息

namespace 是必须提供的属性，serviceEntry 会创建在服务部署的 namespace 中，mtls 也需要知道服务所在的 namespace。

**Comment by FeiYing9** [comment]
> namespace 是必须提供的属性，serviceEntry 会创建在服务部署的 namespace 中，mtls 也需要知道服务所在的 namespace。

赵老师，我不知道我理解的对不对哈：

k8s里服务调用通过`svc.namespace`来发起流量请求，但在SE创建之后直接通过其中配置的host来发送流量？  是不是就不需要`namespace`属性了？

**Comment by zhaohuabing** [comment]
估计应该可以，你把代码这样修改一下试试：如果 aeraki_meta_app_namespace 参数不存在，就使用 "istio-system" 作为 servieEntry 的缺省 namespace。如果测试可以的话提个PR。

**Comment by FeiYing9** [comment]
我们参照赵老师的方案重新设计了自己的方案，与赵老师这套方案不太一样了。 

不过对`meta-protocol-proxy`与`dubbo2istio`的实现真是顶礼膜拜啊

`dubbo2istio`除了上面提到的根节点不可配置，依赖特定属性之外，，感觉还有个缺陷是不断创建协程监听子节点，却没有退出的时机，这样协程会越来越多

**Comment by zhaohuabing** [comment]
协程数量是和服务数量（不是服务实例）相关的，由于一个生产环境中服务数量是可控的，因此协程数量也可控，应该可以接受吧。你们有好的想法欢迎提出了，也欢迎PR。

**Comment by FeiYing9** [comment]
找时间我发邮件给您沟通

**Comment by FeiYing9** [comment]
已发送到邮箱zhaohuabing@gmail.com，请查收
